CREATE TABLE user (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(100) NOT NULL,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  zipcode VARCHAR(10) NOT NULL,
  city VARCHAR(100) NOT NULL,
  adress VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  points INT NOT NULL DEFAULT 0,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  is_ban BOOLEAN NOT NULL DEFAULT FALSE,
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  last_connection TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE (username, email)
);

CREATE TABLE art_piece (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  adress VARCHAR(255),
  city VARCHAR(100) NOT NULL,
  coordinates POINT NOT NULL,
  is_validated BOOLEAN DEFAULT FALSE NOT NULL,
  is_covered BOOLEAN DEFAULT FALSE NOT NULL,
  picture_path VARCHAR(255) NULL,
  description VARCHAR(255),
  points_value INT DEFAULT NULL
);

CREATE TABLE viewed_art_piece (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  art_piece_id INT UNSIGNED,
  user_id INT UNSIGNED,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (art_piece_id) REFERENCES art_piece(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE reported_art_piece (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  art_piece_id INT UNSIGNED,
  user_id INT UNSIGNED,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (art_piece_id) REFERENCES art_piece(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE notifications (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  status BOOLEAN DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  viewed_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);
